name: test_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.1.6
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shimmer: ^2.0.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true

